
export const FETCH_REQUEST_FETCHING = 'FETCH_REQUEST_FETCHING'
export const FETCH_REQUEST_ERROR = 'FETCH_REQUEST_ERROR'
export const FETCH_REQUEST_SUCCESS = 'FETCH_REQUEST_SUCCESS'

export const SET_ERRORS = 'SET_ERRORS'

export const SET_SETTINGS = 'SET_SETTINGS'
export const RESET_SETTINGS = 'RESET_SETTINGS'

export const FETCH_LOGIN_FETCHING = 'FETCH_LOGIN_FETCHING'
export const FETCH_LOGIN_ERROR = 'FETCH_LOGIN_ERROR'
export const FETCH_LOGIN_SUCCESS = 'FETCH_LOGIN_SUCCESS'

export const FETCH_COUNTRIES_FETCHING = 'FETCH_COUNTRIES_FETCHING'
export const FETCH_COUNTRIES_ERROR = 'FETCH_COUNTRIES_ERROR'
export const FETCH_COUNTRIES_SUCCESS = 'FETCH_COUNTRIES_SUCCESS'

export const FETCH_PROVINCES_FETCHING = 'FETCH_PROVINCES_FETCHING'
export const FETCH_PROVINCES_ERROR = 'FETCH_PROVINCES_ERROR'
export const FETCH_PROVINCES_SUCCESS = 'FETCH_PROVINCES_SUCCESS'

export const FETCH_CITIES_FETCHING = 'FETCH_CITIES_FETCHING'
export const FETCH_CITIES_ERROR = 'FETCH_CITIES_ERROR'
export const FETCH_CITIES_SUCCESS = 'FETCH_CITIES_SUCCESS'

export const FETCH_CHECKPROMOCODE_FETCHING = 'FETCH_CHECKPROMOCODE_FETCHING'
export const FETCH_CHECKPROMOCODE_ERROR = 'FETCH_CHECKPROMOCODE_ERROR'
export const FETCH_CHECKPROMOCODE_SUCCESS = 'FETCH_CHECKPROMOCODE_SUCCESS'

export const FETCH_SINGUP_FETCHING = 'FETCH_SINGUP_FETCHING'
export const FETCH_SINGUP_ERROR = 'FETCH_SINGUP_ERROR'
export const FETCH_SINGUP_SUCCESS = 'FETCH_SINGUP_SUCCESS'

export const FETCH_USER_FETCHING = 'FETCH_USER_FETCHING'
export const FETCH_USER_ERROR = 'FETCH_USER_ERROR'
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS'

export const FETCH_FORGOTPASSWORD_FETCHING = 'FETCH_FORGOTPASSWORD_FETCHING'
export const FETCH_FORGOTPASSWORD_ERROR = 'FETCH_FORGOTPASSWORD_ERROR'
export const FETCH_FORGOTPASSWORD_SUCCESS = 'FETCH_FORGOTPASSWORD_SUCCESS'

export const FETCH_FORGOTNUMBER_FETCHING = 'FETCH_FORGOTNUMBER_FETCHING'
export const FETCH_FORGOTNUMBER_ERROR = 'FETCH_FORGOTNUMBER_ERROR'
export const FETCH_FORGOTNUMBER_SUCCESS = 'FETCH_FORGOTNUMBER_SUCCESS'

export const FETCH_CHANGEPASSWORD_FETCHING = 'FETCH_CHANGEPASSWORD_FETCHING'
export const FETCH_CHANGEPASSWORD_ERROR = 'FETCH_CHANGEPASSWORD_ERROR'
export const FETCH_CHANGEPASSWORD_SUCCESS = 'FETCH_CHANGEPASSWORD_SUCCESS'

export const FETCH_EDITPROFILE_FETCHING = 'FETCH_EDITPROFILE_FETCHING'
export const FETCH_EDITPROFILE_ERROR = 'FETCH_EDITPROFILE_ERROR'
export const FETCH_EDITPROFILE_SUCCESS = 'FETCH_EDITPROFILE_SUCCESS'

export const FETCH_LISTOFFERS_FETCHING = 'FETCH_LISTOFFERS_FETCHING'
export const FETCH_LISTOFFERS_ERROR = 'FETCH_LISTOFFERS_ERROR'
export const FETCH_LISTOFFERS_SUCCESS = 'FETCH_LISTOFFERS_SUCCESS'

export const FETCH_ADDPRODUCT_FETCHING = 'FETCH_ADDPRODUCT_FETCHING'
export const FETCH_ADDPRODUCT_ERROR = 'FETCH_ADDPRODUCT_ERROR'
export const FETCH_ADDPRODUCT_SUCCESS = 'FETCH_ADDPRODUCT_SUCCESS'

export const FETCH_LISTSTATEMENTS_FETCHING = 'FETCH_LISTSTATEMENTS_FETCHING'
export const FETCH_LISTSTATEMENTS_ERROR = 'FETCH_LISTSTATEMENTS_ERROR'
export const FETCH_LISTSTATEMENTS_SUCCESS = 'FETCH_LISTSTATEMENTS_SUCCESS'

export const FETCH_CHANGEPINCODE_FETCHING = 'FETCH_CHANGEPINCODE_FETCHING'
export const FETCH_CHANGEPINCODE_ERROR = 'FETCH_CHANGEPINCODE_ERROR'
export const FETCH_CHANGEPINCODE_SUCCESS = 'FETCH_CHANGEPINCODE_SUCCESS'

export const FETCH_FORGETPINCODE_FETCHING = 'FETCH_FORGETPINCODE_FETCHING'
export const FETCH_FORGETPINCODE_ERROR = 'FETCH_FORGETPINCODE_ERROR'
export const FETCH_FORGETPINCODE_SUCCESS = 'FETCH_FORGETPINCODE_SUCCESS'

export const FETCH_CARDIMAGE_FETCHING = 'FETCH_CARDIMAGE_FETCHING'
export const FETCH_CARDIMAGE_ERROR = 'FETCH_CARDIMAGE_ERROR'
export const FETCH_CARDIMAGE_SUCCESS = 'FETCH_CARDIMAGE_SUCCESS'

